name: Deploy to Azure Kubernetes Service using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: YOUR_AKS_CLUSTER_NAME
        resource-group: YOUR_RESOURCE_GROUP_NAME

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install my-app ./charts/my-app \
          --namespace default \
          --create-namespace
